# Derived from official mysql image (our base image)
FROM mysql:latest
MAINTAINER "moaz.refat@hotmail.com"
# Add a database
ARG DB=""
ENV MYSQL_DATABASE ${DB}
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/
