## Pull base image
#FROM python:3.7
FROM python:3.7-alpine3.7

MAINTAINER  "Moaaz Noaman" <moaz.refat@hotmail.com> 
ENV HOME="/home/moaaz"
RUN adduser -D moaaz 
USER moaaz
WORKDIR /home/moaaz/app

ENV PATH="${HOME}:${PATH}"

COPY --chown=moaaz:moaaz . /home/moaaz/app

RUN pip install --user -r requirements.txt --no-cache-dir

EXPOSE 8080
ENTRYPOINT ["python"]
CMD ["./app.py"]
