apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  namespace: employees-$CI_ENVIRONMENT_SLUG
  labels:
    app: employees
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      version: v1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: employees
        image:  moazrefat/employees:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: emp-config