apiVersion: v1
kind: Service
metadata:
  name: employees-lb
  namespace: employees-$CI_ENVIRONMENT_SLUG
  labels:
    app: employees
#  annotations:
#    external-dns.alpha.kubernetes.io/hostname: $CI_ENVIRONMENT_SLUG.k8s.moaaznoaman.com
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
    name: emp-port
  selector:
    app: employees
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: employees
  namespace: employees-$CI_ENVIRONMENT_SLUG
  labels:
    app: employees
  annotations:
    kubernetes.io/ingress.class: nginx-public
spec:
#  tls:
#    - secretName: emp-moaaznoaman
#      hosts:
#        - emp.moaaznoaman.com
  rules:
  - host: $CI_ENVIRONMENT_SLUG.k8s.moaaznoaman.com
    http:
      paths:
      - path: /
        backend:
          serviceName: employees-lb
          servicePort: 8080
      - path: /api/hostname
        backend:
          serviceName: employees-lb
          servicePort: 8080
      - path: /api/details
        backend:
          serviceName: employees-lb
          servicePort: 8080
      - path: /api/register
        backend:
          serviceName: employees-lb
          servicePort: 8080
      - path: /api/health
        backend:
          serviceName: employees-lb
          servicePort: 8080
      - path: /api/info
        backend:
          serviceName: employees-lb
          servicePort: 8080
      - path: /metrics
        backend:
          serviceName: employees-lb
          servicePort: 8080
