apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-db
    name: mysql-db
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-db
    name: mysql-db
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mysql-db:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: db
      git:
        ref: master
        uri: https://github.com/moazrefat/employees.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: "Containerfile"
        buildArgs:
          - name: "DB"
            value: "app"
      # sourceStrategy:
      #   from:
      #     kind: ImageStreamTag
      #     name: mysql:8.0-el8
      #     namespace: openshift
      type: Source
    triggers:
    - github:
        secret: KJHneUyIxbUTqQjXNgEl
      type: GitHub
    - generic:
        secret: SO9X9VjjoVgKT4EEfKdR
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"mysql-db:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"mysql-db\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-db
    name: mysql-db
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql-db
        deployment: mysql-db
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mysql-db
          deployment: mysql-db
      spec:
        containers:
        - env:
          - name: MYSQL_PASSWORD
            value: dontplaywithme
          - name: MYSQL_ROOT_PASSWORD
            value: dontplaywithme
          - name: MYSQL_USER
            value: admin
          image: ' '
          name: mysql-db
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql-db
    name: mysql-db
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql-db
      deployment: mysql-db
  status:
    loadBalancer: {}
kind: List
metadata: {}
