apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: version
    name: version-app
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: version
    name: version-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: version-app:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: version
      git:
        ref: master
        uri: https://github.com/moazrefat/employees.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.9-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: fhVUdxMDb83Z90psG0Bz
      type: GitHub
    - generic:
        secret: t0ln5uFSodeEubk32yYL
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: version
    name: version-app
  spec:
    replicas: 1
    selector:
      app: version
      deploymentconfig: version-app
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: version
          deploymentconfig: version-app
      spec:
        containers:
        - env:
          - name: MYSQL_LB
            value: mysql-db
          image: version-app:latest
          name: version-app
          ports:
          - containerPort: 8080
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - version-app
        from:
          kind: ImageStreamTag
          name: version-app:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: version
    name: version-app
  spec:
    allocateLoadBalancerNodePorts: false
    ports:
    - name: 8080-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: version
      deploymentconfig: version-app
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
metadata: {}
